build:
  main: ./cmd/gocfn
  binary: gocfn
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
brew:
  github:
    owner: b-b3rn4rd
    name: homebrew-tap
  folder: Formula
dockers:
- image: b-b3rn4rd/gocfn
  tag_templates:
    - '{{ .Tag }}'
    - latest
